#!/bin/sh

set -e

lb config noauto \
	--archive-areas "main contrib non-free non-free-firmware" \
	--compression bzip2 \
	--distribution testing \
	--debootstrap-options "--variant=minbase" \
	--bootappend-live 'boot=live components quiet splash' \
	--hdd-label 'SAMPLE_OS' --image-name 'SampleOS' \
	--iso-application 'SampleOS' --iso-publisher 'ya_Bob_Jonez (Mykhailo Stetsiuk)' --iso-volume "SampleOS Trixie $(date +%F)" \
	--memtest memtest86+ \
	--color \
	"${@}"
